
[build]
  command = "npm run build"
  functions = "C:\Users\EVER ROJAS\OneDrive\Escritorio\react-python-twitter\front\netlify\functions"
  publish = "dist"

  
  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

  